package:
  name: pydaq
  version: {{ environ.get("HUTCH") }}

source:
  path: .

build:
  number: 1
  script: python link.py pydaq
  script_env:
    - HUTCH

requirements:
  build:
    - python {{PY_VER}}*,<3
    - future # [py2k]
  run:
    - python {{PY_VER}}*,<3
