package:
  name: pycdb
  version: {{ environ.get("HUTCH") }}

source:
  path: .

build:
  number: 1
  string: py{{ py }}
  script: python make_installer.py pycdb
  script_env:
    - HUTCH
    - DEV_DIR

requirements:
  build:
    - python {{PY_VER}}*
    - future # [py2k]
  run:
    - python {{PY_VER}}*
