# epics-v4 minus pvaPy, which will be built separately and linked to a
# specific numpy release.
package:
  name: epics-v4
  version: "4.6.0"

source:
  url: https://sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  fn: EPICS-CPP-4.6.0.tar.gz

build:
  number: 1

requirements:
  build:
    - epics-base

  run:
    - epics-base

about:
  home: epics-pvdata.sourceforge.net
  license: EPICS Open License
  summary: EPICS V4 Library
