package:
  name: epics-v4
  version: "4.6.0"

source:
  fn: EPICS-CPP-4.6.0.tar.gz
  url: sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  patches:
    - pvapy_autoconf.diff
    - pvapy_makefile.diff
    - pvapy_m4ax.diff

build:
  number: 1
  script_env:
    - EPICS_BASE
    - EPICS_HOST_ARCH

requirements:
  build:
    - epics-base
    - automake
    - autoconf
    - boost

  run:
    - epics-base

about:
  home: epics-pvdata.sourceforge.net
  license: Epics Open License
  summary: EPICS V4 Library
