package:
  name: epics-v4
  version: "4.6.0"

source:
  path: ./temp_source/EPICS-CPP-4.6.0.tar.gz
  fn: EPICS-CPP-4.6.0.tar.gz
  # url: https://sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  # patches:

build:
  number: 1
  script_env:
    - EPICS_BASE
    - EPICS_HOST_ARCH

requirements:
  build:
    - epics-base
    - automake
    - autoconf
    - python
    - numpy
    - boost >=1.63

  run:
    - epics-base

about:
  home: epics-pvdata.sourceforge.net
  license: EPICS Open License
  summary: EPICS V4 Library
