{% set version = "3.0.4" %}
{% set EPICS = '3.14.12.6' %}

package:
  name: pyca
  version: {{ version }}

source:
  url: https://github.com/slaclab/pyca/archive/{{ version }}.tar.gz
  fn: pyca-{{ version }}.tar.gz

build:
  number: 1
  string: py{{ py }}np{{ np }}epics{{ EPICS }}
  script:
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ PY_VER }}*
    - setuptools
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

  run:
    - python {{ PY_VER }}*
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

test:
  imports:
    - pyca
    - psp

about:
  home: https://github.com/slaclab/pyca
  licence: SLAC Open Licence
  summary: Python Channel Access
