package:
  name: pvaPy
  version: "4.6.0"

source:
  path: ../epics-v4/temp_source/EPICS-CPP-4.6.0.tar.gz
  fn: EPICS-CPP-4.6.0.tar.gz
  # url: https://sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  patches:
    - pvobjectcpp.diff
    - pypvdatautilitycpp.diff
    - pypvdatautilityh.diff

build:
  number: 1

requirements:
  build:
    - epics-v4
    - automake
    - autoconf
    - python
    - numpy
    - boost >=1.63

  run:
    - epics-base

about:
  home: epics-pvdata.sourceforge.net
  license: EPICS Open License
  summary: EPICS V4 Library
