package:
  name: pvapy
  version: "4.6.0"

source:
  path: ../temp_source/EPICS-CPP-4.6.0.tar.gz
  # path: {{ environ.get('PREFIX') }}/epics-v4/pvaPy
  # path: {{ EPICS4_BASE }}/pvaPy
  fn: EPICS-CPP-4.6.0.tar.gz
  # url: https://sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  patches:
    - pvobjectcpp.diff
    - pypvdatautilitycpp.diff
    - pypvdatautilityh.diff

build:
  number: 1
  string: np{{ np }}py{{ py }}

requirements:
  build:
    - epics-v4 4.6.0
      #    - automake
      #    - autoconf
    - python
    - numpy
    - boost >=1.63

  run:
    - epics-v4 4.6.0
    - python
    - numpy

test:
  import:
    - pvaccess

about:
  home: epics-pvdata.sourceforge.net
  license: EPICS Open License
  summary: EPICS V4 Library
