# Note that I'm ignoring pvaPy's real versioning, instead opting to pick the
# version number associated with a particular EPICS-CPP release.
# This is a separate build because epics-v4 takes a while to compile and pvaPy
# should be be linked to a numpy release at build.
package:
  name: pvapy
  version: "4.6.0"

source:
  # Full source to make sure we get the associated release of pvaPy
  # Conda caches these files so you don't have to redownload to build both
  url: https://sourceforge.net/projects/epics-pvdata/files/4.6.0/EPICS-CPP-4.6.0.tar.gz
  fn: EPICS-CPP-4.6.0.tar.gz
  patches:
    # Switch to syntax from boost 1.63 because you can get boost with numpy
    # from conda-forge starting at this release.
    - pvobjectcpp.diff
    - pypvdatautilitycpp.diff
    - pypvdatautilityh.diff

build:
  number: 1
  string: np{{ np }}py{{ py }}

requirements:
  build:
    - epics-v4 4.6.0
    - python
    - numpy
    - boost >=1.63

  run:
    - epics-v4 4.6.0
    - python
    - numpy

test:
  import:
    - pvaccess

about:
  home: epics-pvdata.sourceforge.net
  license: EPICS Open License
  summary: EPICS V4 Python Bindings
