{% set version = "3.3.0" %}
package:
    name: pyepics
    version: {{ version }}

source:
    url: https://github.com/pyepics/pyepics/archive/{{ version }}.tar.gz
    fn: pyepics-{{ version }}.tar.gz

build:
    number: 1
    script: |
      export PYEPICS_LIBCA=$PREFIX/lib/libca.so
      export NOLIBCA=1
      echo "Using LIBCA from $PYEPICS_LIBCA"
      python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy
        - epics-base
    run:
        - python
        - numpy
        - epics-base

test:
    imports:
        - epics

about:
    home: http://pyepics.github.io/pyepics/
    license: Epics Open License
    summary: Python interface to Epics Channel Access

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
